[package]
name = "rdvb"
version = "0.1.0"
edition = "2024"

[dependencies]
enum-from-discriminant-derive = { path = "../enum-from-discriminant-derive" }
nix = { version = "0.30.1", features = ["fs", "ioctl"] }
